type Product {
    _id: ID!
    name: String!
    description: String!
    price: Float!
    images: [String!]!
    tags: [String]!
    categories: [String]!
}

input ProductInput {
    name: String!
    description: String!
    price: Float!
    images: [String!]!
    tags: [String]!
    categories: [String]!
}

type Query {
    products: [Product!]!
    product(id: ID!): Product!
}

type Mutation {
    addProduct(data: ProductInput!): Product!
}