type Product {
    _id: ID!
    name: String!
    price: Float!
}

input ProductInput {
    name: String!
    price: Float!
}

type Query {
    products: [Product!]!
    product(id: ID!): Product!
}

type Mutation {
    addProduct(data: ProductInput!): Product!
}